namespace DemoProductsWebAPI.Domain.Entities
{
    /// <summary>
    /// Represents a line item in a shopping cart that contains a product and its quantity.
    /// This is a domain entity that models the relationship between a cart and the products it contains.
    /// 
    /// The ProductCart entity is responsible for:
    /// - Storing the association between a cart and a specific product
    /// - Maintaining the quantity of a product requested in the cart
    /// - Providing navigation to the related Product entity
    /// - Supporting shopping cart operations (add to cart, update quantity, remove)
    /// 
    /// Key characteristics:
    /// - Represents a "line item" or "cart item" in shopping cart terminology
    /// - Contains foreign key reference to Product for data integrity
    /// - Uses Entity Framework Core navigation properties for related data access
    /// - Supports cart operations: add product, update quantity, remove from cart
    /// 
    /// Usage in application layers:
    /// - Domain: Core model for shopping cart items
    /// - Infrastructure: Mapped to database table via Entity Framework Core
    /// - Application: Transferred as ProductCartDto via AutoMapper
    /// - API: Exposed through ProductCartsController endpoints for cart management
    /// </summary>
    public class ProductCart
    {
        /// <summary>
        /// Gets or sets the unique identifier for this cart item.
        /// This is the primary key in the database that uniquely identifies this specific cart line item.
        /// 
        /// Range: Positive integer, auto-generated by SQL Server identity column.
        /// Uniqueness: Guaranteed to be unique within the ProductCart table.
        /// Usage: Used for cart item operations (update quantity, remove from cart).
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the foreign key reference to the Product entity.
        /// This links this cart item to a specific product in the system.
        /// 
        /// Purpose: Maintains referential integrity by enforcing that only existing products can be added to cart.
        /// Constraints: Must reference a valid Product.Id in the database.
        /// Cascade: Deletion of the product should handle cascade behavior (typically restrict or delete cart items).
        /// Usage: Used to look up product details when displaying cart or calculating totals.
        /// </summary>
        public int ProductId { get; set; }

        /// <summary>
        /// Gets or sets the quantity of the product in this cart item.
        /// This represents how many units of the product are requested in the cart.
        /// 
        /// Range: Positive integer (1 or greater in typical business logic).
        /// Constraints: Should not be zero or negative; validation typically enforced at application layer.
        /// Default: Not set during entity creation; must be explicitly assigned.
        /// Usage: Used for calculating cart subtotals, inventory checks, and order fulfillment.
        /// 
        /// Example: ProductCart with ProductId=5 and Quantity=3 means 3 units of product 5 in the cart.
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// Gets or sets the related Product entity that this cart item references.
        /// This is a navigation property that enables eager loading of product details.
        /// 
        /// Purpose: Allows access to product information (name, price, etc.) without separate database query.
        /// Nullability: Nullable because EF Core lazy-loading may return null if product is deleted after cart item created.
        /// Initialization: Populated by Entity Framework Core when using Include() or eager loading.
        /// Performance: Use Include() in LINQ queries to avoid N+1 query problems.
        /// 
        /// Example usage:
        ///     var cartItem = await _context.ProductCarts.Include(c => c.Product).FirstAsync();
        ///     var productName = cartItem.Product?.ProductName; // Safe navigation
        /// </summary>
        public Product? Product { get; set; }
    }
}
