namespace DemoProductsWebAPI.Domain.Entities
{
    /// <summary>
    /// Represents a product entity in the domain model.
    /// This is a core domain entity that contains product information and audit tracking.
    /// 
    /// The Product entity is responsible for:
    /// - Storing product details (name, audit trail)
    /// - Maintaining creation and modification timestamps
    /// - Tracking who created and modified the entity
    /// - Serving as the central domain model for product-related operations
    /// 
    /// This entity is used throughout the application layers:
    /// - Domain: Defines the core business model
    /// - Infrastructure: Maps to database table via Entity Framework Core
    /// - Application: Transferred as ProductDto via AutoMapper
    /// - API: Exposed through ProductsController endpoints
    /// </summary>
    public class Product
    {
        /// <summary>
        /// Gets or sets the unique identifier for the product.
        /// This is the primary key assigned by the database on creation.
        /// Range: Positive integer, auto-generated by SQL Server identity column.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the product.
        /// This is a required field that describes what the product is.
        /// Default: Empty string if not explicitly set.
        /// Constraints: Should not be null; typically limited to 255 characters in database.
        /// </summary>
        public string ProductName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the username or identifier of the user who created this product.
        /// This is an audit field for tracking creation accountability.
        /// Default: Empty string if not explicitly set.
        /// Format: Typically contains the authenticated user's username or ID.
        /// </summary>
        public string CreatedBy { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the timestamp when the product was created.
        /// This is an audit field for tracking creation time.
        /// Format: UTC DateTime value set at the time of entity creation.
        /// Usage: Used for sorting, filtering, and audit trail generation.
        /// </summary>
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// Gets or sets the username or identifier of the user who last modified this product.
        /// This is an optional audit field; null indicates the product has never been modified.
        /// Format: Typically contains the authenticated user's username or ID.
        /// Default: Null (no modifications yet).
        /// </summary>
        public string? ModifiedBy { get; set; }

        /// <summary>
        /// Gets or sets the timestamp when the product was last modified.
        /// This is an optional audit field; null indicates the product has never been modified.
        /// Format: UTC DateTime value set when the entity is updated.
        /// Default: Null (no modifications yet).
        /// Usage: Used to determine if entity has been modified since creation.
        /// </summary>
        public DateTime? ModifiedOn { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Product"/> class with default values.
        /// Used for:
        /// - Entity Framework Core deserialization from database
        /// - Creating product instances when all properties will be set separately
        /// 
        /// Note: Parameterless constructor is required by Entity Framework Core for change tracking.
        /// </summary>
        public Product() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="Product"/> class with specified values.
        /// This constructor is used when creating a new product with initial audit information.
        /// 
        /// Flow: Set Id, ProductName, CreatedBy, CreatedOn from parameters.
        /// ModifiedBy and ModifiedOn remain null as this is a new entity.
        /// </summary>
        /// <param name="id">The unique identifier for the product (typically from database identity)</param>
        /// <param name="productName">The name of the product</param>
        /// <param name="createdBy">The username or identifier of who created the product</param>
        /// <param name="createdOn">The UTC timestamp when the product was created</param>
        public Product(int id, string productName, string createdBy, DateTime createdOn)
        {
            Id = id;
            ProductName = productName;
            CreatedBy = createdBy;
            CreatedOn = createdOn;
        }
    }
}
