namespace DemoProductsWebAPI.Domain.Entities
{
    /// <summary>
    /// Represents a refresh token used for JWT token renewal and authentication session management.
    /// This is a security domain entity that manages long-lived tokens for user authentication.
    /// 
    /// The RefreshToken entity is responsible for:
    /// - Storing refresh tokens issued to authenticated users
    /// - Tracking token expiration to enforce security policies
    /// - Managing token revocation for logout and security breach handling
    /// - Supporting token renewal flow without requiring user re-authentication
    /// - Maintaining user session continuity across API requests
    /// 
    /// Key characteristics:
    /// - Refresh tokens have longer expiration than access tokens (typically days vs minutes)
    /// - Tokens can be explicitly revoked for immediate logout or security purposes
    /// - Used in OAuth 2.0 token refresh flow: POST /auth/refresh with refresh token
    /// - Each user can have multiple active refresh tokens (different devices/sessions)
    /// 
    /// Security considerations:
    /// - Tokens should be cryptographically secure random strings
    /// - Expired tokens should be periodically cleaned from database
    /// - Revoked tokens must be checked before issuing new access tokens
    /// - Should be transmitted only via secure HTTPS channels
    /// - Consider implementing token rotation on refresh for enhanced security
    /// 
    /// Usage in application layers:
    /// - Domain: Core security model for token management
    /// - Infrastructure: Persisted to database, queried during authentication
    /// - Application: Referenced in token validation and refresh handlers
    /// - API: Exposed through AuthController for token refresh endpoints
    /// </summary>
    public class RefreshToken
    {
        /// <summary>
        /// Gets or sets the unique identifier for this refresh token record.
        /// This is the primary key in the database that uniquely identifies this token entry.
        /// 
        /// Range: Positive integer, auto-generated by SQL Server identity column.
        /// Uniqueness: Guaranteed to be unique within the RefreshToken table.
        /// Usage: Used for token lifecycle management (update revocation status, delete expired tokens).
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the actual refresh token string value.
        /// This is the cryptographic token sent to the client for token renewal requests.
        /// 
        /// Format: Typically a long, random cryptographic string (Base64 or hex encoded).
        /// Length: Should be sufficiently long (32+ bytes decoded) for security.
        /// Constraints: Should be unique in the database to prevent token reuse attacks.
        /// Generation: Should be created using a cryptographically secure random number generator.
        /// Default: Empty string if not explicitly set.
        /// 
        /// Security: Never log or expose this token in plain text in production logs.
        /// Storage: Should be hashed in database for additional security (current implementation stores plain).
        /// 
        /// Example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI..."
        /// </summary>
        public string Token { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the user identifier to whom this refresh token was issued.
        /// This links the refresh token to a specific user in the authentication system.
        /// 
        /// Format: Typically the user's unique identifier (GUID or numeric ID from identity system).
        /// Purpose: Used to validate that token refresh request is from the correct user.
        /// Constraints: Must correspond to a valid user in the authentication/identity system.
        /// Usage: When refreshing tokens, verify UserId matches the requesting user's identity.
        /// Default: Empty string if not explicitly set.
        /// 
        /// Security: Always validate that the authenticated user matches the token's UserId.
        /// 
        /// Example: "550e8400-e29b-41d4-a716-446655440000" (GUID) or "12345" (numeric ID)
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the expiration timestamp for this refresh token.
        /// This defines when the token becomes invalid and can no longer be used for renewal.
        /// 
        /// Format: UTC DateTime value representing the expiration moment.
        /// Validation: Token is invalid if current time exceeds this timestamp.
        /// Typical Duration: Usually 7-30 days from token issuance (longer than access token).
        /// Constraints: Should be greater than current UTC time at token creation.
        /// Usage: Checked during token validation to reject expired tokens.
        /// 
        /// Security: Enforce strict expiration; prevent use of expired tokens even if not revoked.
        /// Cleanup: Periodically delete database records where ExpiresOn < UtcNow for storage optimization.
        /// 
        /// Example: A token issued today might expire in 7 days.
        /// Flow: Current time (UtcNow) is compared against ExpiresOn; if UtcNow >= ExpiresOn, token is invalid.
        /// </summary>
        public DateTime ExpiresOn { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this refresh token has been revoked.
        /// A revoked token can no longer be used to obtain new access tokens.
        /// 
        /// Default: False (not revoked) when token is first created.
        /// Purpose: Allows immediate invalidation without deleting the record from database.
        /// Scenarios when revoked:
        ///   - User explicitly logs out
        ///   - Security breach detected (force re-authentication)
        ///   - User password is changed
        ///   - User permissions are modified
        ///   - Token is compromised
        /// 
        /// Validation: During token refresh, check both IsRevoked and ExpiresOn:
        ///     if (token.IsRevoked || token.ExpiresOn &lt; DateTime.UtcNow)
        ///         return Unauthorized(); // Token is invalid
        /// 
        /// Performance: Creating an index on IsRevoked can optimize queries for active tokens.
        /// 
        /// Audit Trail: Consider logging token revocation events with timestamp and reason for compliance.
        /// 
        /// Security: Always check IsRevoked before accepting a token refresh request.
        /// </summary>
        public bool IsRevoked { get; set; }
    }
}
